specVersion: 0.2.0
name: sopo-test
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/cheesekon/sopometa-mba-subquery'
schema:
  file: ./schema.graphql
network:
  endpoint: wss://wss.api.moonbase.moonbeam.network
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1981000
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: contract
        address: "0xfeBC26D030b0ccBA7CB95f52dDEF0A63bd79f8A1"
    assets:
      contract:
        file: './contract.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        # event Listed(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address);
        - handler: handleListedEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Listed(address indexed from,address indexed to,uint256 indexed sopo_id,uint256 nft_id,address nft_programe_address)
              - null
              - null
              - null

    # event Listandforsell(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address,uint256 price);

    # event Forsell(uint256 sopo_id,uint256 price    );

    # event Newoffer(address from,address to,uint256 sopo_id,uint256 price    );

    # event Withdraw(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address,uint32 withdrawout_at);

    # event Selled(address from,address to,uint256 sopo_id,uint32  selled_at,uint256 nft_id,address nft_programe_address,address owner);