specVersion: 0.2.0
name: sopo-test
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/cheesekon/sopometa-mba-subquery'
schema:
  file: ./schema.graphql
network:
  endpoint: >-
    wss://moonbeam-alpha.api.onfinality.io/ws?apikey=52b88ee0-060a-4e8d-a172-a3a4911be386
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  dictionary: 'https://sz.api.subquery.network/sq/subquery/moonbase-alpha-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1772820
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
  - kind: substrate/Moonbeam
    startBlock: 799150
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: "erc721"
        address: "0xe912d5056ECdE3BaB1286E653FC32bd684D3e6C8"
    assets:
      erc721:
        file: "./erc721.abi.json"
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMoonriverEvent
          kind: substrate/MoonbeamEvent
          filter:
            ## Topics that follow Ethereum JSON-RPC log filters
            ## https://docs.ethers.io/v5/concepts/events/
            ## With a couple of added benefits:
            ##  - Values don't need to be 0 padded
            ##  - Event fragments can be provided and automatically converted to their id
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)

              ## Example of OR filter, will capture Transfer or Approval events
              # - - 'Transfer(address indexed from,address indexed to,uint256 value)'
              #   - 'Approval(address indexed owner, address indexed spender, uint256 value)'

              - Transfer(address from,address to,uint256 tokenId)
              ## topics[1] to topics[3] are the indexed values
              - null
              - null
              - null
  - kind: substrate/Moonbeam
    startBlock: 1772820
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        # Must be a key of assets
        abi: contract
        address: "0x7546601D838bebd9108894a557d533311090Dad8"
    assets:
      contract:
        file: './contract.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        # event Listed(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address);
        - handler: handleListedEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Listed(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address)

    # event Listandforsell(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address,uint256 price);

    # event Forsell(uint256 sopo_id,uint256 price    );

    # event Newoffer(address from,address to,uint256 sopo_id,uint256 price    );

    # event Withdraw(address from,address to,uint256 sopo_id,uint256 nft_id,address nft_programe_address,uint32 withdrawout_at);

    # event Selled(address from,address to,uint256 sopo_id,uint32  selled_at,uint256 nft_id,address nft_programe_address,address owner);